.TH ALARMD_SET_DEFAULT_SNOOZE 3 "Oct  5, 2006" "Nokia"

.SH NAME
alarmd_set_default_snooze, alarmd_get_default_snooze \- Set/get default
snooze interval for alarmd

.SH SYNOPSIS
.B #include <alarm_event.h>
.sp
.BI "int alarmd_set_default_snooze(unsigned int " snooze );
.br
.B unsigned int alarmd_get_default_snooze(void);

.SH DESCRIPTION
The
.B alarmd_set_default_snooze()
function will set the default snooze interval in minutes for events in
.B alarmd(8)'s
queue, that haven't set their own. The function will return 1 if the
snooze interval was successfully set and 0 if it was not. On error
you can use
.B alarmd_get_error(3)
to get details why it failed.

The
.B alarmd_get_default_snooze()
gets the default snooze interval used by
.B alarmd(8)
or 0, if fetching the interval failed. Use
.B alarmd_get_error(3)
to get details of the failure.

.SH SEE ALSO
.BR alarmd (8)
.BR alarm_event_add (3)

.SH HISTORY
Oct  5 2006: Initial version of this manual page.

.SH COPYRIGHT
Copyright \(co 2006 Nokia Corporation.

This is free software; see /usr/share/common-licenses/LGPL-2.1 for license
conditions.  There is NO  warranty;  not even for MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.
