#!/sbin/openrc-run

description="Alarm daemon"

depend() {
	need dbus clockd
}

start() {
	if [ -x /usr/sbin/dsmetool ]; then
		/usr/sbin/dsmetool -U user -G users -f "$DAEMON $DAEMON_OPTS"
	else
		start-stop-daemon --start --quiet --exec "$DAEMON" -- $DAEMON_OPTS
	fi
}

stop() {
	if [ -x /usr/sbin/dsmetool ]; then
		/usr/sbin/dsmetool -U user -G users -k "$DAEMON $DAEMON_OPTS"
	else
		start-stop-daemon --stop --oknodo --quiet --exec "$DAEMON"
	fi
}
